#!/bin/sh
#--------------------------------------
# Script Name:  config
# Version:      1.0
# Author:       skurka@ukaachen.de, shuening@ukaachen.de, akombeiz@ukaachen.de
# Date:         25 Oct 24
# Purpose:      Debconf configuration script that prompts for database connection settings for 'aktin-notaufnahme-i2b2'. It collects user inputs for
#               the database connection method and credentials, guiding the installation process.
#--------------------------------------

# Exit on error
set -e

# Source debconf library
. /usr/share/debconf/confmodule

# Ask user how they want to connect to the database
db_input low aktin-notaufnahme/db_conn || true

# If user did not select unix as the connection method
if [ "$RET" != "unix" ]; then
  # Ask for database connection details
  db_input low aktin-notaufnahme/db_host || true
  db_input low aktin-notaufnahme/db_port || true
  db_input low aktin-notaufnahme/db_user || true
  db_input low aktin-notaufnahme/db_pass || true
fi

# Show interface
db_go || true
