#!/bin/sh
#--------------------------------------
# Script Name:  config
# Version:      1.0
# Author:       skurka@ukaachen.de, shuening@ukaachen.de, akombeiz@ukaachen.de
# Date:         29 Oct 24
# Purpose:      Debconf configuration script for 'aktin-notaufnahme-i2b2'.
#               This script prompts the user for database connection settings as defined in the templates file.
#               It collects user inputs for the database connection method and credentials, storing them in Debconf
#               for use during the installation and configuration of the package.
#--------------------------------------

# Exit on error
set -euo

# Source Debconf library
. /usr/share/debconf/confmodule

# Ask user how they want to connect to the database
db_input low __SHARED_PACKAGE__/db_conn || true

# If user did not select unix as the connection method
if [ "$RET" != "unix" ]; then
  # Ask for database connection details
  db_input low __SHARED_PACKAGE__/db_host || true
  db_input low __SHARED_PACKAGE__/db_port || true
  db_input low __SHARED_PACKAGE__/db_user || true
  db_input low __SHARED_PACKAGE__/db_pass || true
fi

# Show interface
db_go || true
