#!/bin/bash
#--------------------------------------
# Script Name:  postinst
# Version:      1.2
# Authors:      skurka@ukaachen.de, shuening@ukaachen.de, akombeiz@ukaachen.de
# Date:         07 Nov 24
# Purpose:      Configures the package after files are unpacked by initializing services, databases, and required configurations to make the package operational.
#--------------------------------------

log_info() { echo -e "\033[0;34m[INFO]\033[0m $1"; }
log_success() { echo -e "\033[0;32m[SUCCESS]\033[0m $1"; }
log_warn() { echo -e "\033[1;33m[WARN]\033[0m $1"; }
log_error() { echo -e "\033[0;31m[ERROR]\033[0m $1" >&2; }

readonly OPERATION="${1}"

source_helper_script() {
  local helper_path="/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/helper.sh"
  log_info "Loading helper script..."
  if [[ ! -f "${helper_path}" ]]; then
    log_error "helper.sh not found at ${helper_path}"
    exit 1
  fi
  . "${helper_path}"
  log_success "Helper script loaded"
}

activate_php_curl_extension() {
  log_info "Configuring PHP curl extension..."
  if ! grep -q "^extension=curl" /etc/php/*/apache2/php.ini; then
    sed -i "s/;extension=curl/extension=curl/" /etc/php/*/apache2/php.ini
    systemctl restart apache2
    log_success "PHP curl extension activated"
  else
    log_info "PHP curl extension already active"
  fi
}

check_postgresql_versions() {
  local pg_versions=$(pg_lsclusters | tail -n +2 | awk '{print $1}' | sort -n | uniq)
  log_info "Checking PostgreSQL versions..."

  if [[ $(echo "${pg_versions}" | wc -l) -gt 1 ]]; then
    log_warn "Multiple PostgreSQL versions detected (${pg_versions})"
    log_warn "Your data is still in the old PostgreSQL version"
    log_warn "Please migrate your data to the new version"
    log_warn "Refer to PostgreSQL documentation or use 'pg_upgrade'"
  else
    log_success "Single PostgreSQL version detected: ${pg_versions}"
  fi
}

init_and_seed_i2b2_database() {
  connect_to_psql
  log_info "Initializing i2b2 database..."
  if [[ $(eval "${PSQL} -l" | grep "i2b2" | wc -l) == 0 ]]; then
    eval "${PSQL} -v ON_ERROR_STOP=1 -f /usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/sql/i2b2_init.sql" >/dev/null
    eval "${PSQL} -v ON_ERROR_STOP=1 -d i2b2 -f /usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/sql/i2b2_db.sql" >/dev/null
    log_success "Database initialized successfully"
  else
    log_info "Database i2b2 already exists"
  fi
}

restore_wildfly_logs() {
  local log_dir="/opt/wildfly/standalone/log"
  local backup_dir="/var/backups/${DPKG_MAINTSCRIPT_PACKAGE}/wildfly_logs"
  log_info "Restoring WildFly logs..."

  mkdir -p "${log_dir}"
  # Restore logs from backup directory if they exist
  if [ -d "${backup_dir}" ] && [ "$(ls -A "${backup_dir}")" ]; then
    cp -r "${backup_dir}/"*.log "${log_dir}/"
    # Remove the backup after successful restore
    rm -rf "${backup_dir}"
    log_success "Logs restored successfully"
  else
    log_info "No logs to restore"
  fi
}

# Function to add a value to a key within the [Unit] section of a systemd service file
add_entry_to_service() {
  local service_name="$1"
  local key="$2"
  local value="$3"
  local service_file="/lib/systemd/system/${service_name}"

  # Check if the key exists in the service file
  if grep -q "^${key}=" "${service_file}"; then
    # Get the current line with the key
    local line
    line="$(grep "^${key}=" "${service_file}")"

    # If the value is not already in the line, append it
    if [[ "${line}" != *"${value}"* ]]; then
      line+=" ${value}"
      # Update the line in the service file
      sed -i "s/^${key}=.*/${line}/" "${service_file}"
    fi
  else
    # Add the key and value after the [Unit] section
    sed -i "/^\[Unit\]$/a ${key}=${value}" "${service_file}"
  fi
}

# TODO: Workaround for insufficient connection handling of WildFly datasources. Replace as soon as possible.
set_wildfly_service_dependency() {
  log_info "Setting up service dependency between Postgresql and Wildfly..."
  add_entry_to_service "wildfly.service" "Requires" "postgresql.service"
  add_entry_to_service "wildfly.service" "After" "postgresql.service"
  log_success "Service dependencies configured"
}

create_wildfly_user() {
  log_info "Setting up WildFly user..."
  if ! id -u wildfly >/dev/null 2>&1; then
    adduser --system --group --disabled-login --home /var/lib/wildfly wildfly
    log_success "WildFly user created"
  else
    log_info "WildFly user already exists"
  fi
}

set_wildfly_permissions() {
  log_info "Setting up Wildfly user permissions..."
  chown -R wildfly:wildfly /opt/wildfly
  log_success "WildFly user permissions set"
}

main() {
  set -euo pipefail
  case "$OPERATION" in
    configure)
      # Runs during installation/upgrade after files have been unpacked
      source_helper_script
      systemctl enable apache2
      check_and_start_service "apache2"
      activate_php_curl_extension
      systemctl enable postgresql
      check_and_start_service "postgresql"
      check_postgresql_versions
      init_and_seed_i2b2_database
      set_wildfly_service_dependency
      create_wildfly_user
      restore_wildfly_logs
      dpkg-trigger --await __TRIGGER_PREFIX__-restore
      set_wildfly_permissions
      systemctl daemon-reload
      systemctl enable wildfly
      check_and_start_service "wildfly"
      ;;
  esac
}

main "$@"
