#!/bin/bash
#--------------------------------------
# Script Name:  postrm
# Version:      1.1
# Author:       skurka@ukaachen.de, shuening@ukaachen.de, akombeiz@ukaachen.de
# Date:         30 Oct 24
# Purpose:      Post-removal script for 'aktin-notaufnahme-i2b2'.
#               Executes after files are deleted. Handles cleanup of configurations and database.
#--------------------------------------

readonly OPERATION="${1}"

deactivate_php_curl_extension() {
  if grep -q "^extension=curl" /etc/php/*/apache2/php.ini; then
    echo "Disabling Apache PHP cURL extension..."
    sed -i "s/^extension=curl/;extension=curl/" /etc/php/*/apache2/php.ini
    echo "Restarting Apache..."
    systemctl restart apache2
  else
    echo "Apache PHP cURL extension is already disabled."
  fi
}

delete_wildfly_user() {
  echo "Deleting WildFly user..."
  if id -u wildfly >/dev/null 2>&1; then
    deluser --remove-home wildfly
    echo "WildFly user deleted."
  else
    echo "WildFly user does not exist."
  fi
}

delete_wildfly_remnants() {
  echo "Deleting WildFly remnants..."
  rm -rf /opt/wildfly/standalone/{tmp,configuration,data,log}
  rm -f /opt/wildfly/standalone/deployments/*.{deployed,failed,isdeploying,pending}
  rm -f /etc/wildfly/wildfly.conf
  echo "WildFly remnants deleted."
}

notify_user_about_services() {
  echo "Note: The following services were installed and enabled during the installation of this package:"
  echo "  - Apache (apache2)"
  echo "  - PostgreSQL (postgresql)"
  echo "These services remain untouched after the package removal. You may disable them if they are no longer needed:"
  echo "  sudo systemctl disable apache2"
  echo "  sudo systemctl disable postgresql"
}

source_temp_helper() {
  local temp_helper="/tmp/${DPKG_MAINTSCRIPT_PACKAGE}_helper.sh"
  if [[ -f "${temp_helper}" ]]; then
    source "${temp_helper}"
  else
    echo "Error: Temporary helper script not found. Cannot proceed with database cleanup."
    exit 1
  fi
}

drop_i2b2_database() {
  source_temp_helper
  connect_to_psql
  wait_for_psql_connection
  if [[ $(eval "${PSQL} -l" | grep "i2b2" | wc -l) -gt 1 ]]; then
    echo "Dropping i2b2 PostgreSQL database and user..."
    eval "${PSQL} -v ON_ERROR_STOP=1" <<EOF >/dev/null
    __I2B2_DROP_STATEMENT__
EOF
  else
    echo "i2b2 database already removed. Skipping..."
  fi
}

remove_temp_helper() {
  rm -f "/tmp/${DPKG_MAINTSCRIPT_PACKAGE}_helper.sh"
}

main() {
  set -euo pipefail
  case "$OPERATION" in
    remove)
      #  Clean up tasks after a successful removal.
      deactivate_php_curl_extension
      delete_wildfly_user
      delete_wildfly_remnants
      notify_user_about_services
      ;;
    purge)
      # Run during a purge to delete all configuration files.
      drop_i2b2_database
      remove_temp_helper
      ;;
    abort-install)
      # Used if installation is interrupted.
      ;;
    abort-upgrade)
      # Clean up after a failed upgrade.
      ;;
    abort-remove)
      # Run if removal fails or is interrupted.
      ;;
  esac
}

main "$@"
