#!/bin/bash
#--------------------------------------
# Script Name:  prerm
# Version:      1.0
# Author:       skurka@ukaachen.de, shuening@ukaachen.de, akombeiz@ukaachen.de
# Date:         25 Oct 24
# Purpose:      Pre-removal script for 'aktin-notaufnahme-i2b2' package. It stops and disables the WildFly service before removal, and during
#               upgrades, it removes service dependencies between WildFly and PostgreSQL.
#--------------------------------------

readonly OPERATION="${1}"

main() {
  set -euo pipefail
  case "$OPERATION" in
    remove)
      echo "Stopping and disabling WildFly service..."
      if systemctl is-active --quiet wildfly; then
        systemctl stop wildfly || true
      else
        echo "WildFly service is not running."
      fi
      systemctl disable wildfly || true
      systemctl daemon-reload
      ;;
    upgrade)
      echo "Removing WildFly-Postgresql service dependencies..."
      if [ -f "/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/helper.sh" ]; then
        . "/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/helper.sh"
        remove_entry_from_service "wildfly.service" "Requires" "postgresql.service"
        remove_entry_from_service "wildfly.service" "After" "postgresql.service"
        systemctl daemon-reload
      else
        echo "Helper script not found; skipping dependency removal."
      fi
      ;;
  esac
}

main "$@"
