version: '3'
services:
  notaufnahme-i2b2-wildfly:
    image: ghcr.io/aktin/notaufnahme-i2b2-wildfly
    hostname: wildfly
    environment:
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - aktin-network
  notaufnahme-i2b2-database:
    image: ghcr.io/aktin/notaufnahme-i2b2-database
    hostname: db
    volumes:
      - source: ./postgresql-data
        target: /var/lib/postgresql/data
        type: bind
        bind:
          create_host_path: true
    networks:
      - aktin-network
  notaufnahme-i2b2-httpd:
    image: ghcr.io/aktin/notaufnahme-i2b2-httpd
    hostname: httpd
    ports:
      - "90:80"
    environment:
      WILDFLY_HOST: wildfly
    networks:
      - aktin-network
networks:
  aktin-network:

