services:
  database:
    image: ${IMAGE_NAMESPACE}-database
    build:
      context: ./build/database
  httpd:
    image: ${IMAGE_NAMESPACE}-httpd
    build:
      context: ./build/httpd
  wildfly:
    image: ${IMAGE_NAMESPACE}-wildfly
    build:
      context: ./build/wildfly
