name: CI/CD Debian

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+**
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: aktin/aktin-github-scripts/.github/workflows/debian-build.yml@main
    with:
      package-name: 'aktin-notaufnahme-i2b2'

  deploy:
    needs: build
    uses: aktin/aktin-github-scripts/.github/workflows/debian-deploy.yml@main